import { readdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import process from 'node:process';

import ts from 'typescript';

const ROOT = import.meta.dirname;
const require = createRequire(import.meta.url);

// every date is computed in UTC. set here, before any worker starts: workers inherit the
// environment, and node applies a TZ change immediately in this process (used by --runInBand).
// a globalSetup module would need a default export, which the lint rules forbid outside configs
const TIME_ZONE = 'UTC';
process.env.TZ = TIME_ZONE;

const CORE_DIR = 'src/core';
const CORE_LINES_THRESHOLD = 90;
const CORE_BRANCHES_THRESHOLD = 90;
const GLOBAL_LINES_THRESHOLD = 70;
const TEST_TIMEOUT_MS = 60_000;

const SOURCE_EXTENSION = /\.tsx?$/;
// tool configs (src/ui/theme/tailwind.config.ts) are read by their tools, never by the app
const EXCLUDED_FILE = /\.(?:test\.tsx?|config\.tsx?|d\.ts)$/;
const EXCLUDED_FOLDERS = new Set(['__tests__', '__fixtures__', '__mocks__']);
// generated by pnpm db:types; its runtime Constants object would count as untested core code
const GENERATED_DB_TYPES = `${CORE_DIR}/repositories/supabase/database.types.ts`;

// keep in sync with isCoveredSource below
const collectCoverageFrom = [
  'app/**/*.{ts,tsx}',
  'src/**/*.{ts,tsx}',
  '!**/*.test.{ts,tsx}',
  '!**/*.config.{ts,tsx}',
  '!**/__tests__/**',
  '!**/__fixtures__/**',
  '!**/__mocks__/**',
  '!**/*.d.ts',
  `!${GENERATED_DB_TYPES}`,
];

export const isCoveredSource = (relativePath) => {
  const segments = relativePath.split(/[\\/]/);
  const fileName = segments.at(-1) ?? '';
  return (
    SOURCE_EXTENSION.test(fileName) &&
    !EXCLUDED_FILE.test(fileName) &&
    !segments.some((segment) => EXCLUDED_FOLDERS.has(segment)) &&
    segments.join('/') !== GENERATED_DB_TYPES
  );
};

// jest fails with "Coverage data for ./src/core/ was not found" when a threshold path matches no
// file, and src/core only holds READMEs until its first source file lands. that first file turns
// the group on and counts at 0 % until it is tested
const hasCoreSource = readdirSync(path.join(ROOT, CORE_DIR), { recursive: true }).some((entry) =>
  isCoveredSource(path.join(CORE_DIR, String(entry))),
);

const coverageThreshold = {
  global: { lines: GLOBAL_LINES_THRESHOLD },
  ...(hasCoreSource && {
    [`./${CORE_DIR}/`]: { lines: CORE_LINES_THRESHOLD, branches: CORE_BRANCHES_THRESHOLD },
  }),
};

// tsc rejects a "paths" pattern or target with more than one wildcard: such an entry fails here
// too, so every wildcard replaced below is the only one of its entry
const WILDCARD = '*';

const withOneWildcardAtMost = (entry) => {
  if (entry.split(WILDCARD).length > 2) {
    throw new Error(
      `tsconfig.json paths entry "${entry}" has more than one "${WILDCARD}": tsconfig allows one at most`,
    );
  }
  return entry;
};

// tsconfig "paths" as jest moduleNameMapper entries: "@core/*" -> "<rootDir>/src/core/$1"
export const aliasesFromPaths = (paths) =>
  Object.fromEntries(
    Object.entries(paths).map(([alias, targets]) => [
      `^${withOneWildcardAtMost(alias)
        .replaceAll(/[.+?^${}()|[\]\\]/g, '\\$&')
        .replaceAll(WILDCARD, '(.*)')}$`,
      targets.map(
        (target) =>
          `<rootDir>/${path.posix.normalize(withOneWildcardAtMost(target)).replaceAll(WILDCARD, '$1')}`,
      ),
    ]),
  );

const aliasesFromTsconfig = () => {
  const tsconfigPath = path.join(ROOT, 'tsconfig.json');
  const { config, error } = ts.readConfigFile(tsconfigPath, ts.sys.readFile);
  if (error) {
    throw new Error(ts.flattenDiagnosticMessageText(error.messageText, '\n'));
  }
  return aliasesFromPaths(config.compilerOptions?.paths ?? {});
};

// test files of each project, relative to the root. testMatch is built from these lists and the
// guard below checks every test file against the same lists, so the two cannot drift.
// no path segment may start with one of {}()+?.^$: on windows jest turns the slash before it into
// a backslash that escapes it, and the pattern matches nothing (src\{ui,core}), so folder
// alternatives are spelled out one pattern each (tools/jest/jest-config-globs.test.mjs)
// core tests are split by extension: a .tsx test renders react (core hooks and providers, with
// @testing-library/react) and runs in jsdom, a .ts test runs in node. a per-file environment
// docblock would keep the node project's setup, whose msw/node server does not load under jsdom
// (its export conditions resolve msw/node to nothing, and jsdom lacks the fetch globals msw needs)
const CORE_TESTS = ['src/core/**/*.test.ts', 'test/core/**/*.test.ts'];
const CORE_DOM_TESTS = ['src/core/**/*.test.tsx', 'test/core/**/*.test.tsx'];
const MOBILE_TESTS = [
  'src/features/**/*.test.{ts,tsx}',
  'src/ui/**/*.test.{ts,tsx}',
  'src/platform/**/*.test.{ts,tsx}',
  'test/app/**/*.test.{ts,tsx}',
  'test/mobile/**/*.test.{ts,tsx}',
];
const PROJECT_TESTS = { core: CORE_TESTS, 'core-dom': CORE_DOM_TESTS, mobile: MOBILE_TESTS };
const TEST_ROOTS = ['app', 'src', 'test'];
const TEST_FILE = /\.test\.tsx?$/;

const toTestMatch = (patterns) => patterns.map((pattern) => `<rootDir>/${pattern}`);

// root-relative paths with forward slashes, as the patterns above are written
const filesUnder = (root) =>
  readdirSync(path.join(ROOT, root), { recursive: true }).map((entry) =>
    path.posix.join(root, ...String(entry).split(path.sep)),
  );

const projectsRunning = (file) =>
  Object.entries(PROJECT_TESTS)
    .filter(([, patterns]) => patterns.some((pattern) => path.posix.matchesGlob(file, pattern)))
    .map(([name]) => name);

// a test file outside every project would never run, and one inside both would run twice:
// either case fails the whole run here instead. matchesGlob skips dot folders, so a test under
// one is reported too: that errs on the loud side
const assertEveryTestInOneProject = () => {
  const misplaced = TEST_ROOTS.flatMap(filesUnder).filter(
    (file) => TEST_FILE.test(file) && projectsRunning(file).length !== 1,
  );
  if (misplaced.length > 0) {
    const projects = Object.entries(PROJECT_TESTS).map(
      ([name, patterns]) => `${name}: ${patterns.join(', ')}`,
    );
    throw new Error(
      `test files outside exactly one jest project: ${misplaced.join(', ')}. ` +
        `move them under one project's paths (${projects.join('; ')})`,
    );
  }
};
assertEveryTestInOneProject();

// the app's babel transform (expo preset, as metro runs it), without the react native preset
const expoPreset = require('jest-expo/jest-preset');
const BABEL_PATTERN = '\\.[jt]sx?$';
const babelTransform = expoPreset.transform[BABEL_PATTERN];
if (!babelTransform) {
  throw new Error(`jest-expo no longer transforms ${BABEL_PATTERN}: update the core project`);
}

// jest 29 cannot require native esm: esm-only dependencies of msw are transformed to commonjs
const CORE_ESM_DEPENDENCIES = ['@open-draft/deferred-promise', 'rettime', 'until-async'];

// any stylesheet import, matched against the module name as written
const CSS_MODULE = '\\.css$';

// the intl-pluralrules polyfill (src/platform/intl-polyfills.ts) ships esm only: jest-expo's ignore
// pattern must let its @formatjs packages through, next to the ones it already transforms
const PNPM_SEGMENT = '(.pnpm|';
const [expoIgnoreFirst, ...expoIgnoreRest] = expoPreset.transformIgnorePatterns;
if (!expoIgnoreFirst?.includes(PNPM_SEGMENT)) {
  throw new Error('jest-expo changed its transformIgnorePatterns: update the mobile project');
}
const mobileTransformIgnorePatterns = [
  expoIgnoreFirst.replace(PNPM_SEGMENT, `${PNPM_SEGMENT}@formatjs|`),
  ...expoIgnoreRest,
];

const shared = {
  rootDir: ROOT,
  cacheDirectory: '<rootDir>/node_modules/.cache/jest',
  // every timer api and the clock are fake (msw and react native testing library run with them);
  // the setup files pin the clock and reset timers before each test (test/core/fixed-clock.ts)
  fakeTimers: { enableGlobally: true },
  restoreMocks: true,
  errorOnDeprecated: true,
};

// both core projects: the app's babel transform and path aliases, no react native preset
const sharedCore = {
  ...shared,
  transform: { '\\.(?:[jt]sx?|mjs)$': babelTransform },
  // pnpm stores packages under node_modules/.pnpm/<name>@<version>/node_modules/<name>
  transformIgnorePatterns: [`/node_modules/(?!(?:\\.pnpm|${CORE_ESM_DEPENDENCIES.join('|')})/)`],
  moduleNameMapper: aliasesFromTsconfig(),
};

/** @type {import('jest').Config} */
const config = {
  // test order within each file is shuffled with a seed printed in the summary (--seed replays it)
  randomize: true,
  // react native requires its components lazily: the first async test of a file that renders one
  // (ScrollView, the router) transforms and instruments it inside the test. that takes up to 3 s
  // with a warm cache and over 30 s with a cold one, as on every ci run, past jest's 5 s default.
  // a hung test still fails, at this timeout. a global option: jest ignores it in a project
  testTimeout: TEST_TIMEOUT_MS,
  collectCoverageFrom,
  coverageThreshold,
  coverageReporters: ['text-summary', 'text', 'lcov'],
  projects: [
    {
      ...sharedCore,
      displayName: 'core',
      // node export conditions: msw/node resolves, and a react native import fails at runtime
      testEnvironment: 'node',
      testMatch: toTestMatch(CORE_TESTS),
      setupFilesAfterEnv: ['<rootDir>/test/core/setup.ts'],
    },
    {
      ...sharedCore,
      displayName: 'core-dom',
      // browser export conditions, as a web app would resolve core; no msw server: network
      // globals throw (test/core/setup-dom.ts)
      testEnvironment: 'jsdom',
      testMatch: toTestMatch(CORE_DOM_TESTS),
      setupFilesAfterEnv: ['<rootDir>/test/core/setup-dom.ts'],
    },
    {
      ...shared,
      displayName: 'mobile',
      preset: 'jest-expo',
      testMatch: toTestMatch(MOBILE_TESTS),
      // nativewind compiles src/ui/theme/global.css in metro only: jest gets an empty module
      moduleNameMapper: { [CSS_MODULE]: '<rootDir>/test/mobile/css-stub.ts' },
      transformIgnorePatterns: mobileTransformIgnorePatterns,
      setupFilesAfterEnv: ['<rootDir>/test/mobile/setup.ts'],
    },
  ],
};

export default config;
