import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import path from 'node:path';
import process from 'node:process';
import { describe, it } from 'node:test';
import { stripVTControlCharacters } from 'node:util';
import assert from 'node:assert/strict';

import config, { singleAuthor, singleAuthorViolation } from '../../commitlint.config.mjs';

const ROOT = path.resolve(import.meta.dirname, '..', '..');
const CO_AUTHOR = 'co-author trailers are not allowed (see CONTRIBUTING.md section 2)';
const GENERATED = 'tool-generated footers are not allowed (see CONTRIBUTING.md section 2)';
const TRAILER = 'Co-authored-by: Someone <someone@example.com>';
const SCISSORS = '# ------------------------ >8 ------------------------';
const CLEAN =
  'feat(library): add +1 progress button\n\nthe button increments the progress by one.\n';

const [isIgnored] = config.ignores;

describe('singleAuthorViolation', () => {
  describe('co-author trailers', () => {
    const cases = [
      ['LF message', `feat: add x\n\n${TRAILER}\n`],
      ['CRLF message', `feat: add x\r\n\r\n${TRAILER}\r\n`],
      ['lowercase trailer', 'feat: add x\n\nco-authored-by: Someone <someone@example.com>'],
      ['uppercase trailer', 'feat: add x\n\nCO-AUTHORED-BY: Someone <someone@example.com>'],
      ['space-indented trailer', `feat: add x\n\n   ${TRAILER}`],
      ['tab-indented trailer', `feat: add x\n\n\t${TRAILER}`],
      [
        'trailer among other trailers',
        `feat: add x\n\nRefs: #12\n${TRAILER}\nSigned-off-by: A <a@b.c>`,
      ],
      ['trailer above the scissors line', `feat: add x\n\n${TRAILER}\n${SCISSORS}\ndiff`],
      ['trailer in a message without body', TRAILER],
    ];
    for (const [name, message] of cases) {
      it(`rejects a ${name}`, () => {
        assert.equal(singleAuthorViolation(message), CO_AUTHOR);
      });
    }
  });

  describe('generated footers', () => {
    const cases = [
      ['"Generated with"', 'feat: add x\n\nGenerated with SomeTool'],
      ['"generated by"', 'feat: add x\n\ngenerated by SomeTool'],
      ['"Generated-by:" trailer', 'feat: add x\n\nGenerated-by: SomeTool'],
      ['"Generated with:" footer', 'feat: add x\n\nGenerated with: SomeTool'],
      ['footer ending the line', 'feat: add x\n\nGenerated with'],
      [
        'footer after an emoji',
        'feat: add x\n\n\u{1F916} Generated with [SomeTool](https://example.com)',
      ],
      ['footer after punctuation', 'feat: add x\n\n-- *Generated by SomeTool*'],
      ['indented footer', 'feat: add x\n\n    generated with SomeTool'],
      ['CRLF footer', 'feat: add x\r\n\r\nGenerated with SomeTool\r\n'],
    ];
    for (const [name, message] of cases) {
      it(`rejects a ${name}`, () => {
        assert.equal(singleAuthorViolation(message), GENERATED);
      });
    }
  });

  describe('compliant messages', () => {
    const cases = [
      ['conventional message with a body', CLEAN],
      ['CRLF conventional message', CLEAN.replaceAll('\n', '\r\n')],
      ['empty message', ''],
      ['commented trailer', `feat: add x\n\n# ${TRAILER}`],
      ['commented trailer without space', `feat: add x\n\n#${TRAILER}`],
      ['commented footer', 'feat: add x\n\n# Generated with SomeTool'],
      ['trailer below the scissors line', `feat: add x\n${SCISSORS}\n${TRAILER}`],
      ['footer below the scissors line', `feat: add x\n${SCISSORS}\nGenerated with SomeTool`],
      ['CRLF trailer below the scissors line', `feat: add x\r\n${SCISSORS}\r\n${TRAILER}\r\n`],
      ['trailer mentioned mid-line', 'docs: explain why Co-authored-by: trailers are rejected'],
      ['"generated by" inside a sentence', 'docs: describe files generated by the build'],
      ['"generated" not followed by with/by', 'feat: add x\n\nGenerated files are ignored.'],
      ['"generated with" glued to a longer word', 'feat: add x\n\nGenerated withheld values.'],
      ['other trailers', 'feat: add x\n\nRefs: #12\nSigned-off-by: A <a@b.c>'],
    ];
    for (const [name, message] of cases) {
      it(`accepts a ${name}`, () => {
        assert.equal(singleAuthorViolation(message), null);
      });
    }
  });

  it('keeps the trailer below a scissors lookalike without "#"', () => {
    const lookalike = SCISSORS.slice(2);
    assert.equal(singleAuthorViolation(`feat: add x\n${lookalike}\n${TRAILER}`), CO_AUTHOR);
  });
});

describe('singleAuthor rule', () => {
  it('passes a clean parsed.raw', () => {
    assert.deepEqual(singleAuthor({ raw: CLEAN }, 'always'), [true, '']);
  });

  it('fails a parsed.raw with a trailer', () => {
    assert.deepEqual(singleAuthor({ raw: `feat: add x\n\n${TRAILER}` }, 'always'), [
      false,
      CO_AUTHOR,
    ]);
  });

  it('defaults to "always"', () => {
    assert.deepEqual(singleAuthor({ raw: `feat: add x\n\n${TRAILER}` }), [false, CO_AUTHOR]);
    assert.deepEqual(singleAuthor({ raw: CLEAN }), [true, '']);
  });

  it('fails closed on "never", even for a clean message', () => {
    const [valid, message] = singleAuthor({ raw: CLEAN }, 'never');
    assert.equal(valid, false);
    assert.match(message, /only supports the "always" condition/);
  });

  it('fails closed on "never" instead of inverting the policy for a violating message', () => {
    const [valid] = singleAuthor({ raw: `feat: add x\n\n${TRAILER}` }, 'never');
    assert.equal(valid, false);
  });

  describe('without parsed.raw', () => {
    it('reads the footer', () => {
      const parsed = { header: 'feat: add x', body: 'details', footer: TRAILER };
      assert.deepEqual(singleAuthor(parsed, 'always'), [false, CO_AUTHOR]);
    });

    it('reads the body', () => {
      const parsed = { header: 'feat: add x', body: 'Generated with SomeTool', footer: null };
      assert.deepEqual(singleAuthor(parsed, 'always'), [false, GENERATED]);
    });

    it('passes a header-only message with null body and footer', () => {
      const parsed = { raw: null, header: 'feat: add x', body: null, footer: null };
      assert.deepEqual(singleAuthor(parsed, 'always'), [true, '']);
    });

    it('falls back to the parts when raw is not a string', () => {
      const parsed = { raw: undefined, header: 'feat: add x', body: null, footer: TRAILER };
      assert.deepEqual(singleAuthor(parsed, 'always'), [false, CO_AUTHOR]);
    });
  });
});

describe('commitlint config', () => {
  it('wires the rule as an error on "always" and keeps default ignores off', () => {
    assert.deepEqual(config.rules['single-author'], [2, 'always']);
    assert.equal(config.plugins[0]?.rules['single-author'], singleAuthor);
    assert.equal(config.defaultIgnores, false);
    assert.equal(config.ignores.length, 1);
  });

  describe('ignores[0] (git-generated headers)', () => {
    const generated = [
      ['merge of a branch', "Merge branch 'dev' into feat/library-progress"],
      ['merge of a remote-tracking branch', "Merge remote-tracking branch 'origin/dev'"],
      ['merge of a pull request', 'Merge pull request #3 from owner/feat/x\n\nfeat: add x'],
      ['merge of a tag', "Merge tag 'v1.0.0'"],
      ['merge of a commit', 'Merge 1a2b3c4 into 5d6e7f8'],
      ['revert', 'Revert "feat: add x"\n\nThis reverts commit 1a2b3c4d.'],
      ['fixup!', 'fixup! feat: add x'],
      ['squash!', 'squash! feat: add x'],
      ['amend!', 'amend! feat: add x\n\nfeat: add y'],
      ['CRLF merge', "Merge branch 'dev'\r\n"],
      ['merge after comment and blank lines', "# a comment\n\nMerge branch 'dev'"],
      ['merge with a trailer below the scissors', `Merge branch 'dev'\n${SCISSORS}\n${TRAILER}`],
    ];
    for (const [name, message] of generated) {
      it(`ignores a compliant ${name}`, () => {
        assert.equal(isIgnored(message), true);
      });
    }

    const notIgnored = [
      ['merge with a co-author trailer', `Merge branch 'dev'\n\n${TRAILER}`],
      ['merge with a generated footer', "Merge branch 'dev'\n\nGenerated with SomeTool"],
      ['revert with a co-author trailer', `Revert "feat: add x"\n\n${TRAILER}`],
      ['fixup! with a co-author trailer', `fixup! feat: add x\n\n${TRAILER}`],
      ['squash! with a generated footer', 'squash! feat: add x\n\ngenerated by SomeTool'],
      ['amend! with a lowercase trailer', 'amend! feat: add x\n\nco-authored-by: A <a@b.c>'],
      ['conventional message', CLEAN],
      ['"Merged" header', 'Merged the branches'],
      ['lowercase merge header', "merge branch 'dev'"],
      ['revert without quotes', 'Revert the last change'],
      ['fixup! without a space', 'fixup!feat: add x'],
      ['"Merge" with a short hash', 'Merge 1a2b3c into dev'],
      ['merge header only in the body', `feat: add x\n\nMerge branch 'dev'`],
    ];
    for (const [name, message] of notIgnored) {
      it(`does not ignore a ${name}`, () => {
        assert.equal(isIgnored(message), false);
      });
    }
  });
});

// end to end through the commitlint cli (a direct dev dependency): its node api packages
// (@commitlint/load, @commitlint/lint) are not resolvable from the root with pnpm's isolated layout
const requireFromHere = createRequire(import.meta.url);
const CLI = path.join(
  path.dirname(requireFromHere.resolve('@commitlint/cli/package.json')),
  'cli.js',
);

const runCommitlint = (message) =>
  new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [CLI], {
      cwd: ROOT,
      env: { ...process.env, FORCE_COLOR: '0', NO_COLOR: '1' },
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    let output = '';
    child.stdout.on('data', (chunk) => (output += String(chunk)));
    child.stderr.on('data', (chunk) => (output += String(chunk)));
    child.on('error', reject);
    child.on('close', (code) => {
      resolve({ code, output: stripVTControlCharacters(output) });
    });
    child.stdin.end(message);
  });

describe('commitlint cli with the real config', { concurrency: true }, () => {
  it('accepts a clean conventional message', async () => {
    const { code, output } = await runCommitlint(CLEAN);
    assert.equal(code, 0, output);
  });

  it('rejects a co-author trailer', async () => {
    const { code, output } = await runCommitlint(`feat: add x\n\n${TRAILER}\n`);
    assert.notEqual(code, 0);
    assert.match(output, /co-author trailers are not allowed.*\[single-author\]/);
  });

  it('rejects a generated footer', async () => {
    const { code, output } = await runCommitlint('feat: add x\n\nGenerated with SomeTool\n');
    assert.notEqual(code, 0);
    assert.match(output, /tool-generated footers are not allowed.*\[single-author\]/);
  });

  it('accepts a compliant merge message despite the conventional rules', async () => {
    const { code, output } = await runCommitlint("Merge branch 'dev' into feat/library-progress\n");
    assert.equal(code, 0, output);
  });

  it('rejects a merge message with a co-author trailer', async () => {
    const { code, output } = await runCommitlint(`Merge branch 'dev'\n\n${TRAILER}\n`);
    assert.notEqual(code, 0);
    assert.match(output, /\[single-author\]/);
  });

  it('rejects a non-conventional message', async () => {
    const { code, output } = await runCommitlint('add stuff\n');
    assert.notEqual(code, 0);
    assert.match(output, /\[type-empty\]/);
  });
});
